# Generated by Django 3.1.4 on 2021-08-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='column',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KanbanManager.kanbancolumn'),
            preserve_default=False,
        ),
    ]
