# Generated by Django 3.1.4 on 2021-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanManager', '0002_kanbancard_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='description',
            field=models.TextField(default='This is a test Project used to showcase the website'),
            preserve_default=False,
        ),
    ]
