# Generated by Django 3.1.4 on 2021-08-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanManager', '0005_auto_20210820_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KanbanManager.kanbanboard'),
            preserve_default=False,
        ),
    ]
