# Generated by Django 3.1.4 on 2021-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanManager', '0006_kanbancard_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='attached',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='card_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='estimated',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
